version: '3'

networks:
  net-sccs:

services:

  vault:
    container_name: vault
    image: vault
    ports:
      - "8200:8200"
    environment:
      - 'VAULT_DEV_ROOT_TOKEN_ID=myroot'
      - 'VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200'
    restart: always
    networks:
      - net-sccs

  config-server:
    container_name: config-server
    image: hyness/spring-cloud-config-server
    #build: 
    # - context: $PWD/build/
    ports:
      - "8888:8888"
    volumes:
      - $PWD/volumes/config:/config
    environment:
      - BANNER_LOCATION=file:/config/banner.txt
    networks:
      - net-sccs
    depends_on:
      - vault
